### ISSUE TITLE
大佬，能不能借用一下你的部分爬到的数据，诚心感谢啊

### ISSUE THREAD

**Issue by websec123** [samrayleung/jd_spider#15]

**Comment by samrayleung** [comment]
你可以自己运行爬虫程序，一天也可以爬取约100W 的数据．

**Comment by websec123** [comment]
我试了，但是环境方面有点问题，我一直没解决，我只需要十来万条就行，真的感谢大佬，发我qq -2932174294，给你发个红包呗

**Comment by samrayleung** [comment]
有什么问题可以以issue 的形式发到Github, 我可以试着帮忙解决:)

**Comment by websec123** [comment]
from jd_comment.db import init_mongodb
from jd_comment.items import CommentItem,CommentSummaryItem。这个地方出现错误，导入这个类出现问题了，相同的地方还有
from jd.items import ParameterItem，不知道怎么解决

**Comment by samrayleung** [comment]
你是怎么运行项目的, 截图一下的你运行命令和运行目录
