### ISSUE TITLE
能不能写个java版本的出来啊

### ISSUE THREAD

**Issue by ExtremeYu** [samrayleung/jd_spider#2]
用webmagic？？？

**Comment by samrayleung** [comment]
其实爬虫是跟语言无关的，区别只是某种语言的特性和第三方库是否可以很好地支持爬虫。使用 Python 的好处就是可以快速开发出原型，甚至成品。至于Java, 个人觉得比较适合写大型的项目工程，用来写爬虫并不是不可以，只是有点大材小用的感觉。如果你喜欢的话，你也可以使用 webmagic 来编写同样的代码的。因为逻辑都是一样的嘛，只是语言间有差异。
