### ISSUE TITLE
京东前端策略更改了吧，这样的抓取不到了

### ISSUE THREAD

**Issue by zhangxiaobaidepython** [samrayleung/jd_spider#3]

**Comment by samrayleung** [comment]
出了什么问题？有报错么？

**Comment by zhangxiaobaidepython** [comment]
https://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv118416&productId={}&score=0&sortType=5&page={}&pageSize=10访问不到，什么东西都没有

**Comment by samrayleung** [comment]
你有先去爬取商品的信息, 过了一段时间再去爬取评论的信息么? 其实这里两只不同的爬虫,一只是爬取商品信息, 一只是爬取商品评论信息的, 爬取评论的爬虫依赖于爬取商品的爬虫的

**Comment by zhangxiaobaidepython** [comment]
如果单独要抓某个商品的评论的话，能直接请求到json吗，我没有找到prouductPageComments这个文件

**Comment by samrayleung** [comment]
如果想要爬取某个商品的评论, 也是可以的, 但是我写的爬虫就不适用于这种情况. 你可以自己根据我写的爬取评论的爬虫进行修改, 商品的评论是通过json 的形式进行 异步请求的.

**Comment by zhangxiaobaidepython** [comment]
3Q
