### ISSUE TITLE
爬取页数限制

### ISSUE THREAD

**Issue by tokey66363** [samrayleung/jd_spider#8]
现在某东的评论好像只能爬99页，手动翻页也只能翻到100
self.comment_url = "https://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv118416&productId={}&score=0&sortType=5&page={}&pageSize=10"

**Comment by samrayleung** [comment]
是的，在我的博文[两只蠢萌的爬虫](http://samray.xyz/%E4%B8%A4%E5%8F%AA%E8%A0%A2%E8%90%8C%E7%9A%84%E7%88%AC%E8%99%AB)里，我就有吐槽:

>商品的评论也是以 sku-id 为参数通过异步的方式进行请求的，构造请求的方法跟价格类 似，也不需过多赘述。只是想要吐嘈一下的是，京东的评论是只能一页页向后翻的，不能 跳转。还有一点就是，即使某样商品有 10+w 条评论，最多也只是返回 100 页的数据。 略坑
